### ISSUE TITLE
Error on launching ?

### ISSUE THREAD

**Issue by MrSimh** [vlegoff/tsunami#72]
Hello,
Can't wait to try this project and having fun with
Currently i have an error i dont manage to pass

![image](https://user-images.githubusercontent.com/41760482/179468692-7ebd9e26-b58b-4e33-90be-da5871e03f49.png)

I have tried to install the vector module wich is not the solution because that module was created after this code was done
I have tried a lot of version of python but he is still here
And i have tried a version of tsunami before the 12/09/2013, when the import was done, and its seems working (03/2013 its ok)
When "Vector" is added it doesn't work anymore

I dont understand how to fix this any help ?

Thank you

**Comment by vincent-lg** [comment]
Hi,
Unfortunately, Tsunami's support was dropped a few years back.  The code was written in French so it sounded like I would be the only one using it.
`SimpleVector` was a C binding to speed the navigation module which handled sailing.  I still have this binding around (it's a simple C binding for vectors).  Speed was important, because there could be thousands (if not millions) of coordinates to handle and keeping them in C was easier.
If you really want to try Tsunami and don't care about the navigation module, you can disable it through configuration, I believe.  Navigation is a secondary module, so it's not exactly needed, it just adds commands and objects.  If navigation is important, I can provide you with the binding.  I'm afraid you'll have to compile in on whatever version of Python you're using.  Easy to do on Linux but a bit bothersome on Windows!  Tsunami itself was dropped back when Python 3.4 was the most stable version.  I don't know if it handles newer versions, though it probably should, seeing as it's (mostly) dependence-free.
I would encourage you to migrate to another MUD engine, in Python if you prefer.  I'm currently working on one (TalisMUDS), though it's not really production-worthy yet.  Another alternative is Evennia, which is stable and fun to use.  Neither implement a sailing system out of the box, though.
HTH,
Vincent

**Comment by MrSimh** [comment]
Hi,
Thank you, it's a very complete answer.
I will take a look on Evennia and TalisMUDS,
but yes, I would like to try all the same with the "SimpleVector", and in the worst case I would look to disable the navigation 👍 
Thx

**Comment by vincent-lg** [comment]
Okay. I've committed and pushed a slight modification (Tsunami refused to run on `Python 3.8+`, it's now fixed).  I've also pushed `SimpleVector`: https://github.com/vincent-lg/SimpleVector

The way to install it is (basically) simple.  Just run `python setup.py install` inside of the directory.  But since the module is in C, you'll need a compiler matching your Python version.  Easy on Linux (I don't even think you need to install anything) but a bit more complex on Windows.  As for Mac, I have no idea.

If you have trouble with `cgi.escape` once you start TalisMUD, make sure to pull from Github (`git pull`), this function was deprecated (and dropped in Python 3.8).

You might have some warnings when starting TalisMUD because Python has become more responsible and emits warning on some syntax that shouldn't have been used in the first place.

Also, don't hesitate to report on TalisMUD / what you need in a MUD engine.  The answer might help me giving you better advice, as our expectation vary a lot.

Hope that helps,

**Comment by Jookia** [comment]
Here's how I did it:

```
git clone https://github.com/vincent-lg/tsunami
cd tsunami
python3 -m venv venv
source venv/bin/activate
git clone https://github.com/vincent-lg/SimpleVector
pip install SimpleVector/.
sed -i 's/collections.Hashable/collections.abc.Hashable/g' lib/yaml/constructor.py
python src/kassie.py
```

I had to add the sed to fix an error in 3.10.

**Comment by MrSimh** [comment]
i try tonight, thx a lot 👍

**Comment by MrSimh** [comment]
Its working very well, thank you both
